package com.example.restservice;


public class Sessions {
    public String GetSession(){
		return "{\r\n   \"program\":\"stay relevant stay on top\",\r\n   \"topic\":\"Azure DevOps\",\r\n   \"presenter\":\"Vishal Karki\",\r\n   \"Agenda\":{\r\n      \"Section1\":\"DevOps philosophy\",\r\n      \"Section2\":\"Tool walkaround\",\r\n      \"Section3\":\"Deploy a Restful app service\"\r\n   }\r\n}";
	}
}
