trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

stages:
# Build Stage
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    
    steps:
    - task: Maven@3
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'

    - task: CopyFiles@2
      displayName: 'Copy Files to artifact staging directory'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/target/*.jar'
        TargetFolder: $(Build.ArtifactStagingDirectory)

    - upload: $(Build.ArtifactStagingDirectory)
      artifact: drop

- stage: Dev
  displayName: 'Dev'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - template: templates/t_deployWebApp.yml # template to deploy env
    parameters:  
      environmentName: "Dev"  
      webAppName: 'saasdev'

- stage: UAT
  displayName: 'UAT'
  dependsOn: Dev
  condition: succeeded()  
  jobs:
  - template: templates/t_deployWebApp.yml # template to deploy env
    parameters:  
      environmentName: "UAT"  
      webAppName: 'saasuat'

- stage: Prod
  displayName: 'Prod'
  dependsOn: UAT
  condition: succeeded()
  jobs:
  - template: templates/t_deployWebApp.yml # template to deploy env
    parameters:  
      environmentName: "Prod"  
      webAppName: 'saasprod'
